name: first-github-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: macos-latest
    steps:
        - name: hello
          run: echo "hello, world"
        - name: bye
          run: echo "goodbye!"
